services:
  db:
    image: postgres:14.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: r3y_Dr4c
      POSTGRES_DB: ocw_db
    ports:
      - 5432:5432

  backend:
    build: 
      context: ./ocw-backend
      dockerfile: Dockerfile
    container_name: ocw-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - ./orders-system-backend:/usr/src/app
    ports:
    - "8000:8000"
    depends_on:
      - db

volumes:
  db-data: