# Generated by Django 5.1 on 2024-11-19 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_location_identifier_alter_product_identifier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='last_updated',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='stockmovement',
            old_name='product_stock',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='stockmovement',
            old_name='quantity_stock',
            new_name='quantity',
        ),
    ]
