# Generated by Django 5.1 on 2024-11-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stockmovement_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='received',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reception',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='delivery',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
