# FROM node:20.12-alpine

# # Set the working directory in the container
# WORKDIR /app

# # Copy package.json and package-lock.json
# COPY package*.json ./

# # Install dependencies
# RUN npm ci

# # Ejecutar el script postinstall para las dependencias nativas de electron
# RUN npm run postinstall

# # Copy the rest of the application code
# COPY . .

# # Start Vite and Electron
# # CMD ["sh", "-c", "npm run dev"]
# # CMD ["npm", "run", "dev"]

# # Exponer el puerto para Vite
# EXPOSE 5173

# # Establece la variable de entorno DISPLAY
# ENV DISPLAY=host.docker.internal:0

# # Comando para iniciar el servidor Vite y Electron
# CMD ["sh", "-c", "npm run build && electron-builder"]


# Usa una imagen de Node.js como base
FROM node:20.12

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias y ejecuta postinstall
RUN npm ci && npm run postinstall

# Copia el resto del código de la aplicación al contenedor
COPY . .

# Expone el puerto que usará Vite
EXPOSE 5173

# Establece la variable de entorno DISPLAY
ENV DISPLAY=host.docker.internal:0

# Comando para iniciar el servidor y la aplicación Electron
CMD ["npm", "run", "dev"]